spring:
  application:
    name: fahrten-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fahrten-service
  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: scooter
      schema-action: CREATE_IF_NOT_EXISTS
server:
  port: 8083